import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import tw from "tailwind-styled-components";
import dbConnect from "../util/mongodb";
// https://codesandbox.io/s/piffv?file=/src/pages/api/chat.ts
import * as proccess from "child_process";
const Home: NextPage = () => {
  const Container = tw.div`
  bg-indigo-600
`;

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1
        className="text-3xl font-bold underline"
        onClick={() => console.log("helloo")}
      >
        Hello world!
      </h1>
    </Container>
  );
};

export default Home;
export async function getServerSideProps() {
  const db = await dbConnect();
  const pythonScript = proccess.spawn("python", [
    "util/python/main.py",
    "Hello Python",
    "111",
  ]);
  pythonScript.stdout.on("data", (data) => {
    console.log(data.toString());
  });
  return {
    props: {},
  };
}
